PACKAGE_NAME="uwrl-vs035zsm"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="panel-vs035zsm"
DEST_MODULE_LOCATION[0]="/kernel/drivers/gpu/drm/panel"

AUTOINSTALL="yes"

MAKE[0]="make all"
CLEAN="make clean"

